### PR TITLE
Fix: Unknown "spaceless" tag

### PR DESCRIPTION
**Pull request by blankse**
| Q             | A
| ------------- | ---
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Fixed tickets | 

I get an error in Pimcore X with Twig 3:
image

### CODE REVIEW

**Comment by blankse** [comment]
@solverat Can you review it?

**Comment by scrummer** [comment]
@blankse This one is a bit tricky though because the `apply` tag was introduced first in Twig 2.9. As this bundle currently supports Pimcore 6.x and Pimcore's requirement is twig ^2.4 this could have some impact to older installations.
I think this is worth a thought when finally making this bundle pimcore X ready but (and then locking the current version for pimcore 6.x).

For now I would just suggest you to overwrite view yourself until we decided how to proceed on this.

BR

**Comment by dpfaffenbauer** [comment]
@scrummer this bundle is quite small, branching off for X would not be a big deal. if things don't get moving from a dachcom side, I will have to fork certain stuff anyway

**Comment by blankse** [comment]
@scrummer For this reason I add the requirment to the composer. If someone would stay to twig < 2.9, composer will not update this repo. But Pimcore 6.x would be work also with twig >= 2.9.

**Comment by solverat** [comment]
done with #32 .

**Comment by blankse** [comment]
@solverat Readme/Docs are still wrong

**Comment by solverat** [comment]
@blankse sorry, I don't get it. What exactly is wrong?

**Comment by blankse** [comment]
@solverat In the README is still the `{% spaceless %}` tag

**Comment by solverat** [comment]
damn, missed that. fixed! thank you!

**Pull request closed without merging**
