### PR TITLE
[P11] add twig >= 3.9 (only) suppport

### PR DESCRIPTION
**Pull request by solverat**
| Q             | A                                                  |
|---------------|----------------------------------------------------|
| Bug fix?      | yes                                             |
| New feature?  | yes                                             |
| BC breaks?    | no                                                 |
| Deprecations? | no                                             |
| Fixed tickets | #45 

Starting with 3.1, Emailizr only supports Twig 3.9

### CODE REVIEW

**Comment by dpfaffenbauer** [comment]
@solverat doesn't this break Pimcore features like glossary or custom block rendering?

**Comment by solverat** [comment]
@dpfaffenbauer not sure, what you mean. It's basically the same as before. We're just using yield instead of echo and the new CaptureNode instead of the ob_get_clean.

**Comment by dpfaffenbauer** [comment]
Pimcore itself doesn't work with twig 3.9. you require it and pimcore is conflicting it.

**Comment by solverat** [comment]
Ah, ok. Well, you can't install emailizr 3.1, as long pimcore doesn't support twig 3.9. But this conflict in pimcore is just temporarily. 

For now: 
- emailizr 3.0 => with conflict
- emailizr 3.1 => twig 3.9 support

**Comment by dpfaffenbauer** [comment]
@solverat you know how temporary stuff is in Pimcore right ;) Just wanted to make sure you know that emailizr is incompatible with Pimcore now. I don't see the point in this quick change when Pimcore is not ready yet.

**Pull request merged**
